
go_classification <- c(
  "purine ribonucleotide metabolic process" = "Metabolism & mitochondrial/energy processes",
  "regulation of leukocyte activation" = "Immune & inflammatory response",
  "proton transmembrane transport" = "Transport, ion homeostasis & vesicles",
  "regulation of organelle assembly" = "Development, differentiation & morphogenesis",
  "regulation of transferase activity" = "Protein/RNA synthesis, processing & turnover",
  "morphogenesis of an epithelium" = "Development, differentiation & morphogenesis",
  "immune effector process" = "Immune & inflammatory response",
  "immune response-regulating signaling pathway" = "Immune & inflammatory response",
  "mitochondrial translation" = "Metabolism & mitochondrial/energy processes",
  "cell activation involved in immune response" = "Immune & inflammatory response",
  
  "positive regulation of response to external stimulus" = "Stress response, cell death & microenvironment",
  "actin filament-based movement" = "Muscle structure, development & physiology",
  "T cell activation" = "Immune & inflammatory response",
  "protein localization to nucleus" = "Protein/RNA synthesis, processing & turnover",
  "muscle contraction" = "Muscle structure, development & physiology",
  "activation of immune response" = "Immune & inflammatory response",
  "regulation of autophagy" = "Protein/RNA synthesis, processing & turnover",
  "epithelial tube morphogenesis" = "Development, differentiation & morphogenesis",
  "regulation of protein kinase activity" = "Protein/RNA synthesis, processing & turnover",
  "regulation of kinase activity" = "Protein/RNA synthesis, processing & turnover",
  
  "positive regulation of apoptotic process" = "Stress response, cell death & microenvironment",
  "intracellular monoatomic ion homeostasis" = "Transport, ion homeostasis & vesicles",
  "regulation of cell activation" = "Immune & inflammatory response",
  "regulation of protein transport" = "Transport, ion homeostasis & vesicles",
  "positive regulation of programmed cell death" = "Stress response, cell death & microenvironment",
  "regulation of vesicle-mediated transport" = "Transport, ion homeostasis & vesicles",
  "renal system development" = "Development, differentiation & morphogenesis",
  "response to oxidative stress" = "Stress response, cell death & microenvironment",
  "myeloid cell differentiation" = "Immune & inflammatory response",
  "protein targeting" = "Protein/RNA synthesis, processing & turnover",
  
  # Enriched
  "regulation of system process" = "Development, differentiation & morphogenesis",
  "regulation of lymphocyte activation" = "Immune & inflammatory response",
  "regulation of epithelial cell proliferation" = "Development, differentiation & morphogenesis",
  "positive regulation of protein phosphorylation" = "Protein/RNA synthesis, processing & turnover",
  "muscle system process" = "Muscle structure, development & physiology",
  "leukocyte differentiation" = "Immune & inflammatory response",
  "pattern specification process" = "Development, differentiation & morphogenesis",
  "carbohydrate derivative catabolic process" = "Metabolism & mitochondrial/energy processes",
  
  "striated muscle tissue development" = "Muscle structure, development & physiology",
  "negative regulation of immune system process" = "Immune & inflammatory response",
  "positive regulation of locomotion" = "Muscle structure, development & physiology",
  "leukocyte mediated immunity" = "Immune & inflammatory response",
  "positive regulation of cell adhesion" = "Development, differentiation & morphogenesis",
  "regulation of body fluid levels" = "Transport, ion homeostasis & vesicles",
  "cytokine-mediated signaling pathway" = "Immune & inflammatory response",
  "cellular response to abiotic stimulus" = "Stress response, cell death & microenvironment",
  "cellular response to environmental stimulus" = "Stress response, cell death & microenvironment",
  "positive regulation of cell motility" = "Muscle structure, development & physiology",
  
  "regulation of response to biotic stimulus" = "Immune & inflammatory response",
  "regulation of hormone levels" = "Transport, ion homeostasis & vesicles",
  "positive regulation of defense response" = "Immune & inflammatory response",
  "cellular response to lipid" = "Metabolism & mitochondrial/energy processes",
  "blood circulation" = "Transport, ion homeostasis & vesicles",
  "muscle organ development" = "Muscle structure, development & physiology",
  "inorganic ion homeostasis" = "Transport, ion homeostasis & vesicles",
  "positive regulation of cell adhesion" = "Development, differentiation & morphogenesis",
  "renal system development" = "Development, differentiation & morphogenesis",
  
  "angiogenesis" = "Development, differentiation & morphogenesis",
  "regulation of vesicle-mediated transport" = "Transport, ion homeostasis & vesicles",
  "regulation of cell cycle phase transition" = "Development, differentiation & morphogenesis",
  "regulation of cell activation" = "Immune & inflammatory response",
  "regulation of response to biotic stimulus" = "Immune & inflammatory response",
  "negative regulation of cell cycle process" = "Development, differentiation & morphogenesis",
  "defense response to virus" = "Immune & inflammatory response",
  "immune response-regulating cell surface receptor signaling pathway" = "Immune & inflammatory response",
  "energy derivation by oxidation of organic compounds" = "Metabolism & mitochondrial/energy processes",
  "lymphocyte differentiation" = "Immune & inflammatory response",
  
  "positive regulation of response to external stimulus" = "Stress response, cell death & microenvironment",
  "nucleic acid catabolic process" = "Protein/RNA synthesis, processing & turnover",
  "phospholipid metabolic process" = "Metabolism & mitochondrial/energy processes",
  "vacuole organization" = "Transport, ion homeostasis & vesicles",
  "positive regulation of MAPK cascade" = "Stress response, cell death & microenvironment",
  "glycoprotein biosynthetic process" = "Protein/RNA synthesis, processing & turnover",
  "skeletal system development" = "Development, differentiation & morphogenesis",
  "vesicle organization" = "Transport, ion homeostasis & vesicles",
  "RNA catabolic process" = "Protein/RNA synthesis, processing & turnover",
  "protein processing" = "Protein/RNA synthesis, processing & turnover",
  
  "regulation of protein transport" = "Transport, ion homeostasis & vesicles",
  "positive regulation of proteolysis" = "Protein/RNA synthesis, processing & turnover",
  "regulation of cell activation" = "Immune & inflammatory response",
  "regulation of leukocyte activation" = "Immune & inflammatory response",
  "inorganic ion homeostasis" = "Transport, ion homeostasis & vesicles",
  "vesicle organization" = "Transport, ion homeostasis & vesicles",
  "cell chemotaxis" = "Immune & inflammatory response",
  "negative regulation of immune system process" = "Immune & inflammatory response",
  "positive regulation of secretion" = "Transport, ion homeostasis & vesicles",
  "protein localization to extracellular region" = "Transport, ion homeostasis & vesicles",
  
  "response to peptide hormone" = "Stress response, cell death & microenvironment",
  "regulation of neurogenesis" = "Development, differentiation & morphogenesis",
  "muscle tissue development" = "Development, differentiation & morphogenesis",
  "positive regulation of locomotion" = "Development, differentiation & morphogenesis",
  "muscle organ development" = "Development, differentiation & morphogenesis",
  "regulation of nervous system development" = "Development, differentiation & morphogenesis",
  "positive regulation of cell motility" = "Development, differentiation & morphogenesis",
  "epithelial tube morphogenesis" = "Development, differentiation & morphogenesis",
  "response to bacterium" = "Immune & inflammatory response",
  "response to xenobiotic stimulus" = "Stress response, cell death & microenvironment",
  
  "myeloid cell differentiation" = "Immune & inflammatory response",
  "mesenchyme development" = "Development, differentiation & morphogenesis",
  "leukocyte migration" = "Immune & inflammatory response",
  "negative regulation of locomotion" = "Development, differentiation & morphogenesis",
  "renal system development" = "Development, differentiation & morphogenesis",
  "response to oxidative stress" = "Stress response, cell death & microenvironment",
  "leukocyte differentiation" = "Immune & inflammatory response",
  "positive regulation of MAPK cascade" = "Stress response, cell death & microenvironment",
  "cellular response to abiotic stimulus" = "Stress response, cell death & microenvironment",
  
  "monoatomic cation homeostasis" = "Transport, ion homeostasis & vesicles",
  "regulation of kinase activity" = "Stress response, cell death & microenvironment",
  "intracellular monoatomic cation homeostasis" = "Transport, ion homeostasis & vesicles",
  "regulation of transferase activity" = "Protein/RNA synthesis, processing & turnover",
  "regulation of nervous system development" = "Development, differentiation & morphogenesis",
  "response to virus" = "Immune & inflammatory response",
  "intracellular monoatomic ion homeostasis" = "Transport, ion homeostasis & vesicles",
  "regulation of epithelial cell proliferation" = "Development, differentiation & morphogenesis",
  
  "homophilic cell adhesion via plasma membrane adhesion molecules" = "Neural/innervation & signaling",
  "ribosomal small subunit biogenesis" = "Protein/RNA synthesis, processing & turnover",
  "ribosome biogenesis" = "Protein/RNA synthesis, processing & turnover",
  "ribosomal large subunit biogenesis" = "Protein/RNA synthesis, processing & turnover",
  "alpha-beta T cell activation involved in immune response" = "Immune & inflammatory response",
  "alpha-beta T cell differentiation involved in immune response" = "Immune & inflammatory response",
  "CD4-positive, alpha-beta T cell differentiation involved in immune response" = "Immune & inflammatory response",
  "T-helper cell differentiation" = "Immune & inflammatory response",
  "positive regulation of long-term synaptic potentiation" = "Neural/innervation & signaling",
  "T-helper 17 cell differentiation" = "Immune & inflammatory response",
  
  "axonogenesis" = "Neural/innervation & signaling",
  "axon development" = "Neural/innervation & signaling",
  "sensory organ development" = "Neural/innervation & signaling",
  "positive regulation of locomotion" = "Muscle structure, development & physiology",
  "positive regulation of cell motility" = "Muscle structure, development & physiology",
  "response to hypoxia" = "Stress response, cell death & microenvironment",
  "gland development" = "Stress response, cell death & microenvironment",
  "cell growth" = "Stress response, cell death & microenvironment",
  "response to wounding" = "Stress response, cell death & microenvironment",
  "positive regulation of cell migration" = "Muscle structure, development & physiology",
  
  "Wnt signaling pathway" = "Neural/innervation & signaling",
  "muscle tissue development" = "Muscle structure, development & physiology",
  "intracellular monoatomic ion homeostasis" = "Transport, ion homeostasis & vesicles",
  "regulation of system process" = "Stress response, cell death & microenvironment",
  "regulation of membrane potential" = "Transport, ion homeostasis & vesicles",
  "cell-matrix adhesion" = "Muscle structure, development & physiology",
  "blood circulation" = "Stress response, cell death & microenvironment",
  "hemostasis" = "Stress response, cell death & microenvironment",
  "regulation of monoatomic ion transmembrane transporter activity" = "Transport, ion homeostasis & vesicles",
  "potassium ion transmembrane transport" = "Transport, ion homeostasis & vesicles",
  
  "regulation of system process" = "Stress response, cell death & microenvironment",
  "regulation of neurogenesis" = "Neural/innervation & signaling",
  "regulation of metal ion transport" = "Transport, ion homeostasis & vesicles",
  "embryonic organ development" = "Muscle structure, development & physiology",
  "regulation of nervous system development" = "Neural/innervation & signaling",
  "regulation of neuron projection development" = "Neural/innervation & signaling",
  "regulation of monoatomic ion transport" = "Transport, ion homeostasis & vesicles",
  "leukocyte migration" = "Immune & inflammatory response",
  "epithelial cell development" = "Muscle structure, development & physiology",
  "muscle cell differentiation" = "Muscle structure, development & physiology"
)


